In [1]:
# this is a cell; you can write and run code
print('hello, I am a cell') # press shift+Enter to run it

hello, I am a cell


In [2]:
# import Numpy library
import numpy as np

# Matrices

In [3]:
# matrices are numpy arrays
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]) # list of lists; each list corresponds to a row
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [4]:
A.shape # rows x columns

(5, 3)

In [5]:
# Basic indexing (Python uses 0-based indexing): matrix[row,column]
A[4,2] # entry in row 4 and column 2;

15

In [6]:
A[0,0]

1

In [7]:
# row 1, all the columns
A[1,:]

array([4, 5, 6])

In [8]:
# column 2, all the rows
A[:,2]

array([ 3,  6,  9, 12, 15])

In [9]:
A[:,:] # returns A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [10]:
# column 0, rows 0,1,2,4
A[[0,1,2,4],0]

array([ 1,  4,  7, 13])

In [11]:
# all columns, rows 0,1,2,4
A[[0,1,2,4],:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [13, 14, 15]])

In [12]:
# column 0, rows 1 through 4 (1,2,3,4)
A[[1,2,3,4],0]

array([ 4,  7, 10, 13])

In [13]:
# better: use slicing
A[1:5,0]     #first index:last index+1

array([ 4,  7, 10, 13])

In [14]:
# columns 1 through 2; rows 0 through 3
A[0:4,1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [15]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [16]:
# column 1, rows 2 through the last row
A[2:,1]

array([ 8, 11, 14])

In [17]:
#columns 1 through the last column, rows 1 through the last row
A[1:,1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12],
       [14, 15]])

# Random matrices

In [18]:
A = np.random.randn(10,4)
A

array([[ 1.28639223, -1.25165599, -0.03987848, -0.92648109],
       [-0.67783813, -0.21613042, -1.82634485, -0.96274431],
       [-0.74328624, -0.78728595,  0.11754715, -0.40895675],
       [ 0.02950917,  0.48927545, -1.74309344, -1.71337861],
       [-1.3510657 ,  0.35662466,  0.65840912, -0.7678289 ],
       [-1.77923241,  1.47619547,  0.99959124, -0.13936338],
       [-0.39909012, -0.15237308, -1.30425158, -0.56188749],
       [ 0.33462487, -0.11572418, -0.15124376, -1.15695468],
       [ 0.55609849, -1.69061733, -0.51189518,  0.63470826],
       [-1.97978908, -1.00096243,  1.19025505,  0.70040379]])

# Broadcasting

In [19]:
# example 1: matrix + row
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
r = np.array([[1,2,3]])
A+r # add r to each row of A

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [20]:
# example 2: matrix + column
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.array([[1],[2],[3]])
A+c # add c to each column of A

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [21]:
# example 3: matrix + scalar
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
s = 10
A+s # add s to each entry of A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
# example 4: column + row
c = np.array([[1],[2],[3]])
r = np.array([[3,2,1]])
c+r

array([[4, 3, 2],
       [5, 4, 3],
       [6, 5, 4]])

# Matrix multiplication

In [23]:
n = 100
A = np.random.randn(n,n) # nxn random matrix
B = np.random.randn(n,n) # nxn random matrix

In [24]:
def mat_multiply(A,B):
    m,n = A.shape
    p,q = B.shape
    if n!=p: # if n is not equal p
        print('error: A and B do not have compatible shapes')
    else: # multiply AB
        C = np.zeros([m,p]) # initialize C as the zero matrix
        for i in range(m):
            for j in range(p):
                for k in range(n):
                    C[i,j] +=  A[i,k]*B[k,j]
    return C

In [25]:
C = mat_multiply(A,B)

In [26]:
# check that it works; use @ for matrix multiplication
C-A@B

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Loosing your loops

In [27]:
# timeit is a usefull magic command to time the execution
%timeit C = mat_multiply(A,B) # it takes about 1 second 

1 s ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
# matrix times a matrix
%timeit C = A@B  # it takes less than 100 microseconds (0.0001 seconds)

41.3 µs ± 271 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
